name: ci

on:
  push:

jobs:
  docker:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./app/
          file: app/etc/docker/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ghcr.io/bitfis/azure-simple-setup/python-app:latest
